


global ScheduleTask
global SkipTaskSchedule ; Skips the current task and schedule (does not wait for clocks to finish)

global EnterThread ; Used on interrupt handlers

extern KeGlobalCR3
extern Pmgrt
global __InterruptCheckHalt
extern CpuManagementTable
extern GlobalThreadPreemptionPriorities

extern ApicTimerBaseQuantum
extern ApicTimerClockCounter
extern TimerIncrementerCpuId

; DEFINES
	APIC	 equ 0xFEE00000
	APIC_ID		equ 0x20
	APIC_EOI equ APIC + 0x0B0
	APIC_TIMER_INITIAL_COUNT equ APIC + 0x380
	
	BASE_TIMER_TICKS equ 1800
	APIC_PROCESSORID equ APIC + 0x20
	TPPL_MAX equ 100
	KRNL_DS equ 0x10
	PREEMPTION_STATE_MAX equ 56 ;7 * 8 MAX + 1, When this value is reached, Preemption State Resets
	
	GLOBAL_USER_PMGRT_VIRTUAL_ADDRESS equ 0x20000
	VIRTUAL_PMGRT_TSD equ GLOBAL_USER_PMGRT_VIRTUAL_ADDRESS + 32
	VIRTUAL_PMGRT_RAX equ VIRTUAL_PMGRT_TSD
	VIRTUAL_PMGRT_RBX equ VIRTUAL_PMGRT_TSD + 8
; PRIORITY PTR OFFSETS
	PRIORITY_CLASS_INDEX_IDLE equ 0
	PRIORITY_CLASS_INDEX_LOW equ 8
	PRIORITY_CLASS_INDEX_BELOW_NORMAL equ 0x10
	PRIORITY_CLASS_INDEX_NORMAL equ 0x18
	PRIORITY_CLASS_INDEX_ABOVE_NORMAL equ 0x20
	PRIORITY_CLASS_INDEX_HIGH equ 0x28
	PRIORITY_CLASS_INDEX_REALTIME equ 0x30

; PMGRT OFFSETS
	SCHEDULER_ENABLE	equ 0
	CPU_TIME_CALCULATION			equ 4
	CPU_COUNT		equ 8
	IDLE_CPU_TIME			equ 16
	SCHEDULER_CPU_TIME		equ 24
	;TASK_SCHEDULER_DATA equ 32
	THREAD_LIST_PTR_COUNT equ 104
	PRIORITY_CLASSES equ 160
	LP_INITIAL_PRIORITY_CLASSES equ 216
	INITIAL_PRIORITY_CLASSES equ 272


; CPU MGMT TABLE
	CPM_INITIALIZED equ 0
	CPM_PROCESSORID equ 4
	CPM_TOTAL_THREADS EQU 0x10
	CPM_NUM_READY_THREADS EQU 0x50
	CPM_THREAD_QUEUES EQU 0x90
	CPM_CURRENT_THREAD EQU 0xC8
	CPM_SELECTED_THREAD EQU 0xD0
	CPM_TOTAL_CLOCKS EQU 0xE0 ; 128 Bit value
	CPM_READY_ON_CLOCK EQU 0xF0 ; 128 Bit
	CPM_HIGHEST_PRIORITY_THREAD EQU 0x170
	CPM_SYSTEM_IDLE_THREAD EQU 0x1B0
	CPM_SYSTEM_INTERRUPTS_THREAD EQU 0x1B8
	CPM_FORCE_NEXT_THREAD EQU 0x1C0
	CPM_CURRENT_CPU_TIME EQU 0x1C8
	CPM_ESTIMATED_CPU_TIME EQU 0x1D0
	CPM_HIGH_PRECISION_TIME equ 0x1D8
	CPM_IRQ_CONTROL_TABLE EQU 0x1E0

; THREAD_WAITING_QUEUE

THREAD_WAITING_QUEUE_NEXT equ 0x1000

; PROCESS THREAD TABLE
	TH_STATE equ 0
	TH_THREAD_ID equ 0x08
	TH_PROCESS equ 0x10
	TH_PROCESSORID equ 0x18
	TH_THREAD_PRIORITY equ 0x1C
	TH_TIME_BURST equ 0x20
	TH_WAITING_QUEUE_INDEX equ 0x24
	TH_WAITING_QUEUE equ 0x28
	TH_SCHEDULING_QUANTUM equ 0x30
	TH_READY_AT equ 0x34 ; 128 Bit Value
	TH_CONTROL_MUTEX equ 0x44
	TH_EXIT_CODE equ 0x4C
	TH_REGISTERS equ 0x54

	TH_REGISTER_SIZE equ 0xC0
	TH_STACK equ 0x114
	TH_CPU_TIME equ 0x11C
	TH_VIRTUAL_STACK_POINTER equ 0x124
	TH_CLIENT equ 0x12C
	TH_REMOVE_IOWAIT_AFTER equ 0x134
	TH_ATTEMPT_REMOVE_IOWAIT equ 0x138
	TH_REMAINING_CLOCKS equ 0x13C
	TH_SLEEP_UNTIL equ 0x140 ; 128 Bit Value
	TH_LAST_CALCULATION_TIME equ 0x150 ; 128 Bit Value


; REGISTERS (Packs are 64 Byte width (1 ZMM Register) )

_RAX equ TH_REGISTERS
_RBX equ TH_REGISTERS + 8
_RCX equ TH_REGISTERS + 0x10
_RDX equ TH_REGISTERS + 0x18
_RDI equ TH_REGISTERS + 0x20
_RSI equ TH_REGISTERS + 0x28
_R8 equ TH_REGISTERS + 0x30
_R9 equ TH_REGISTERS + 0x38
_RIP equ TH_REGISTERS + 0x40
_CS equ TH_REGISTERS + 0x48
_RFLAGS equ TH_REGISTERS + 0x50
_RSP equ TH_REGISTERS + 0x58

; PACK OF UINT16 (UINT64)(ds,ss,gs,fs)
_DS equ TH_REGISTERS + 0x60
_SS equ TH_REGISTERS + 0x62
_GS equ TH_REGISTERS + 0x64
_FS equ TH_REGISTERS + 0x66

_ES equ TH_REGISTERS + 0x68
_CR3 equ TH_REGISTERS + 0x70
_XSAVE equ TH_REGISTERS + 0x78
_R10 equ TH_REGISTERS + 0x80
_R11 equ TH_REGISTERS + 0x88
_R12 equ TH_REGISTERS + 0x90
_R13 equ TH_REGISTERS + 0x98
_R14 equ TH_REGISTERS + 0xA0
_R15 equ TH_REGISTERS + 0xA8
_RBP equ TH_REGISTERS + 0xB0


; SEGS : means 16 bit ds,ss,gs,fs
; RESV : Reserved

; MM16 (XMM [SSE])

; Pack 0
__MM16_RAXRBX equ TH_REGISTERS
__MM16_RCXRDX equ TH_REGISTERS + 0x10
__MM16_RDIRSI equ TH_REGISTERS + 0x20
__MM16_R8R9 equ TH_REGISTERS + 0x30

; Pack 1
__MM16_RIPCS equ TH_REGISTERS + 0x40
__MM16_RFLAGSRSP equ TH_REGISTERS + 0x50
__MM16_SEGSES equ TH_REGISTERS + 0x60
__MM16_CR3XSAVE equ TH_REGISTERS + 0x70

; Pack 2
__MM16_R10R11 equ TH_REGISTERS + 0x80
__MM16_R12R13 equ TH_REGISTERS + 0x90
__MM16_R14R15 equ TH_REGISTERS + 0xA0
__MM16_RBPRESV equ TH_REGISTERS + 0xB0

; MM32 (YMM [AVX])

; Pack 0
__MM32_RAXRBXRCXRDX equ TH_REGISTERS
__MM32_RDIRSIR8R9 equ TH_REGISTERS + 0x20

; Pack 1
__MM32_RIPCSRFLAGSRSP equ TH_REGISTERS + 0x40
__MM32_SEGSESCR3XSAVE equ TH_REGISTERS + 0x60

; Pack 2

__MM32_R10R11R12R13 equ TH_REGISTERS + 0x80
__MM32_R14R15RBPRESV equ TH_REGISTERS + 0xA0

; MM64 (ZMM (AVX512))
__MM64_RAXRBXRCXRDXRDIRSIR8R9 equ TH_REGISTERS
__MM64_RIPCSRFLAGSRSPSEGSESCR3XSAVE equ TH_REGISTERS + 0x40
__MM64_R10R11R12R13R14R15RBPRESV equ TH_REGISTERS + 0x80

__MM16_NUM_PRIORITY_CLASS_LOOP equ 4 ; NUM_PRIORITY_CLASSES / 2
__MM32_NUM_PRIORITY_CLASS_LOOP equ 2
__MM64_NUM_PRIORITY_CLASS_LOOP equ 1 ; AVX512 Can read all 64 byte data with 1 instruction (EVEX.vmovdqu zmm0, mm512)

; STATE
	THS_PRESENT equ 1
	THS_RUNNABLE equ 2
	THS_ALIVE equ 4
	THS_IOWAIT equ 8
	THS_REGISTRED equ 0x20
	THREAD_READY equ (THS_PRESENT | THS_RUNNABLE | THS_ALIVE | THS_REGISTRED)
	THS_IDLE equ 0x40
	THS_IOPIN equ 0x100
	THS_SLEEP equ 0x200
	THS_MANUAL equ 0x400

extern SystemSpaceBase

KERNEL_CR3 equ 0x9000

SYSTEM_SPACE_CPUMGMT equ 0x200000

APIC_INITIAL_COUNT equ 0x380
APIC_CURRENT_COUNT equ 0x390

CPU_MGMT_SHIFT equ 15


extern TimerClocksPerSecond
extern ApicTimerClockQuantum
extern HpetMainCounterAddress


; HPET Definitions
extern HpetNumClocks ; QWORD
extern HpetFrequency

PROCESS_PRIORITY_CLASS equ 0x26