BOOT_POINTER_TABLE_MAGIC equ 0xEEF7C8D9
BOOT_POINTER_TABLE_STRMAGIC equ 'PRTP'

; DWORD Aligned Structure

BPTOFF_ENTRY_SIZE equ 0xC ; DWORD
BPTOFF_NUM_ENTRIES equ 0x10 ; DWORD
BPTOFF_ENTRIES_OFFSET equ 0x14 ; DWORD

; (CLUSTER_CHAIN_TYPE : FAT32) Setup manually on other file systems

BPTOFF_KERNEL_CLUSTER_START equ 0x18 ; QWORD
BPTOFF_KERNEL_FILE_NUM_CLUSTERS equ 0x20 ; DWORD
BPTOFF_ALLOCATION_TABLE_LBA equ 0x24
BPTOFF_DATA_CLUSTERS_LBA equ 0x2C
CLUSTER_END_OF_CHAIN equ 0x0FFFFFFF

BPT_ENTRY_CLUSTER_START equ 0 ; QWORD
BPT_ENTRY_NUM_CLUSTERS equ 8 ; DWORD
BPT_ENTRY_PATH_LENGTH equ 0xC ; WORD
BPT_ENTRY_PATH equ 0xE ; String

BPT_MAX_PATH_LENGTH equ 0x100