#pragma once
#include <stdint.h>
#include <krnltypes.h>

#define SOD_INVALID_ACPI_TABLE 0xF0020
#define SOD_ACPI_ENABLE_FAILED 0xF0021
#define SOD_MEMORY_MANAGEMENT 0xF0022
#define SOD_INITIALIZATION 0xF0023
#define SOD_LESS_MEMORY 0xF0001
#define SOD_OUT_OF_RESOURCES 0xF002
#define SOD_PROCESS_CREATION_FAILED 0xF0024
#define SOD_PROCESS_MANAGEMENT 0xF0025
#define SOD_DRIVER_ERROR 0xF0026
#define SOD_INVALID_OEM_LOGO 0xF0027
#define SOD_PECSAM 0xF0028
#define SOD_FS_INITIALIZATION 0xF0029
#define SOD_RESOURCE_LOAD 0xF002A
#define SOD_SYSTEM_LOADING 0xF002B
#define SOD_MEDIA_MANAGEMENT 0xF002C
#define SOD_PROCESSOR_INITIALIZATION 0xF002D
#define SOD_INTERRUPT_MANAGEMENT 0xF002E
#define SOD_DEVICE_MANAGEMENT 0xF002F

void SOD(unsigned int code, char* message);
void KERNELAPI KeSetDeathScreen(UINT64 DeathCode, UINT16* Msg, UINT16* Description, UINT16* SupportLink);


#define SET_SOD_OUT_OF_RESOURCES SOD(SOD_OUT_OF_RESOURCES, "OUT OF RESOURCES")
#define SET_SOD_LESS_MEMORY SOD(SOD_LESS_MEMORY, "LESS MEMORY")
#define SET_SOD_INVALID_ACPI_TABLE SOD(SOD_ACPI_ENABLE_FAILED, "INVALID ACPI TABLE")
#define SET_SOD_MEMORY_MANAGEMENT SOD(SOD_MEMORY_MANAGEMENT, "MEMORY MANAGEMENT")
#define SET_SOD_INITIALIZATION SOD(SOD_INITIALIZATION, "OS INITIALIZATION")
#define SET_SOD_ACPI_ENABLE_FAILED SOD(SOD_ACPI_ENABLE_FAILED, "ACPI ENABLE FAILED")
#define SET_SOD_DRIVER_ERROR SOD(SOD_DRIVER_ERROR, "DRIVER ERROR")
#define SET_SOD_RESOURCE_LOAD SOD(SOD_RESOURCE_LOAD, "FAILED TO LOAD RESOURCES")
#define SET_SOD_PROCESS_MANAGEMENT SOD(SOD_PROCESS_MANAGEMENT, "PROCESS MANAGEMENT")
#define SET_SOD_MEDIA_MANAGEMENT SOD(SOD_MEDIA_MANAGEMENT, "MEDIA MANAGEMENT")
#define SET_SOD_INTERRUPT_MANAGEMENT SOD(SOD_INTERRUPT_MANAGEMENT, "INTERRUPT MANAGEMENT")

